package simplepets.brainsynder.nms;

import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.entity.monster.Shulker;

public class EntitySelector {
    public static final EntityType<? extends Mob> ALLAY = EntityType.ALLAY;
    public static final EntityType<? extends Mob> ARMADILLO = EntityType.ARMADILLO;
    public static final EntityType<? extends ArmorStand> ARMOR_STAND = EntityType.ARMOR_STAND;
    public static final EntityType<? extends Mob> AXOLOTL = EntityType.AXOLOTL;
    public static final EntityType<? extends Mob> BAT = EntityType.BAT;
    public static final EntityType<? extends Mob> BEE = EntityType.BEE;
    public static final EntityType<? extends Mob> BLAZE = EntityType.BLAZE;
    public static final EntityType<? extends Mob> BOGGED = EntityType.BOGGED;
    public static final EntityType<? extends Mob> BREEZE = EntityType.BREEZE;
    public static final EntityType<? extends Mob> CAMEL = EntityType.CAMEL;
    public static final EntityType<? extends Mob> CAT = EntityType.CAT;
    public static final EntityType<? extends Mob> CAVE_SPIDER = EntityType.CAVE_SPIDER;
    public static final EntityType<? extends Mob> CHICKEN = EntityType.CHICKEN;
    public static final EntityType<? extends Mob> COD = EntityType.COD;
    public static final EntityType<? extends Mob> COPPER_GOLEM = EntityType.COPPER_GOLEM;
    public static final EntityType<? extends Mob> COW = EntityType.COW;
    public static final EntityType<? extends Mob> CREAKING = EntityType.CREAKING;
    public static final EntityType<? extends Mob> CREEPER = EntityType.CREEPER;
    public static final EntityType<? extends Mob> DOLPHIN = EntityType.DOLPHIN;
    public static final EntityType<? extends Mob> DONKEY = EntityType.DONKEY;
    public static final EntityType<? extends Mob> DROWNED = EntityType.DROWNED;
    public static final EntityType<? extends Mob> ELDER_GUARDIAN = EntityType.ELDER_GUARDIAN;
    public static final EntityType<? extends Mob> ENDERMAN = EntityType.ENDERMAN;
    public static final EntityType<? extends Mob> ENDERMITE = EntityType.ENDERMITE;
    public static final EntityType<? extends Mob> EVOKER = EntityType.EVOKER;
    public static final EntityType<? extends Mob> FOX = EntityType.FOX;
    public static final EntityType<? extends Mob> FROG = EntityType.FROG;
    public static final EntityType<? extends Mob> GHAST = EntityType.GHAST;
    public static final EntityType<? extends Mob> GIANT = EntityType.GIANT;
    public static final EntityType<? extends Mob> GLOW_SQUID = EntityType.GLOW_SQUID;
    public static final EntityType<? extends Mob> GOAT = EntityType.GOAT;
    public static final EntityType<? extends Mob> GUARDIAN = EntityType.GUARDIAN;
    public static final EntityType<? extends Mob> HAPPY_GHAST = EntityType.HAPPY_GHAST;
    public static final EntityType<? extends Mob> HOGLIN = EntityType.HOGLIN;
    public static final EntityType<? extends Mob> HORSE = EntityType.HORSE;
    public static final EntityType<? extends Mob> HUSK = EntityType.HUSK;
    public static final EntityType<? extends Mob> ILLUSIONER = EntityType.ILLUSIONER;
    public static final EntityType<? extends Mob> IRON_GOLEM = EntityType.IRON_GOLEM;
    public static final EntityType<? extends Mob> LLAMA = EntityType.LLAMA;
    public static final EntityType<? extends Mob> MAGMA_CUBE = EntityType.MAGMA_CUBE;
    public static final EntityType<? extends Mob> MOOSHROOM = EntityType.MOOSHROOM;
    public static final EntityType<? extends Mob> MULE = EntityType.MULE;
    public static final EntityType<? extends Mob> OCELOT = EntityType.OCELOT;
    public static final EntityType<? extends Mob> PANDA = EntityType.PANDA;
    public static final EntityType<? extends Mob> PARROT = EntityType.PARROT;
    public static final EntityType<? extends Mob> PHANTOM = EntityType.PHANTOM;
    public static final EntityType<? extends Mob> PIG = EntityType.PIG;
    public static final EntityType<? extends Mob> PIGLIN = EntityType.PIGLIN;
    public static final EntityType<? extends Mob> PIGLIN_BRUTE = EntityType.PIGLIN_BRUTE;
    public static final EntityType<? extends Mob> PILLAGER = EntityType.PILLAGER;
    public static final EntityType<? extends Mob> POLAR_BEAR = EntityType.POLAR_BEAR;
    public static final EntityType<? extends Mob> PUFFERFISH = EntityType.PUFFERFISH;
    public static final EntityType<? extends Mob> RABBIT = EntityType.RABBIT;
    public static final EntityType<? extends Mob> RAVAGER = EntityType.RAVAGER;
    public static final EntityType<? extends Mob> SALMON = EntityType.SALMON;
    public static final EntityType<? extends Mob> SHEEP = EntityType.SHEEP;
    public static final EntityType<? extends Shulker> SHULKER = EntityType.SHULKER;
    public static final EntityType<? extends Mob> SILVERFISH = EntityType.SILVERFISH;
    public static final EntityType<? extends Mob> SKELETON = EntityType.SKELETON;
    public static final EntityType<? extends Mob> SKELETON_HORSE = EntityType.SKELETON_HORSE;
    public static final EntityType<? extends Mob> SLIME = EntityType.SLIME;
    public static final EntityType<? extends Mob> SNIFFER = EntityType.SNIFFER;
    public static final EntityType<? extends Mob> SNOW_GOLEM = EntityType.SNOW_GOLEM;
    public static final EntityType<? extends Mob> SPIDER = EntityType.SPIDER;
    public static final EntityType<? extends Mob> SQUID = EntityType.SQUID;
    public static final EntityType<? extends Mob> STRAY = EntityType.STRAY;
    public static final EntityType<? extends Mob> STRIDER = EntityType.STRIDER;
    public static final EntityType<? extends Mob> TADPOLE = EntityType.TADPOLE;
    public static final EntityType<? extends Mob> TRADER_LLAMA = EntityType.TRADER_LLAMA;
    public static final EntityType<? extends Mob> TROPICAL_FISH = EntityType.TROPICAL_FISH;
    public static final EntityType<? extends Mob> TURTLE = EntityType.TURTLE;
    public static final EntityType<? extends Mob> VEX = EntityType.VEX;
    public static final EntityType<? extends Mob> VILLAGER = EntityType.VILLAGER;
    public static final EntityType<? extends Mob> VINDICATOR = EntityType.VINDICATOR;
    public static final EntityType<? extends Mob> WANDERING_TRADER = EntityType.WANDERING_TRADER;
    public static final EntityType<? extends Mob> WARDEN = EntityType.WARDEN;
    public static final EntityType<? extends Mob> WITCH = EntityType.WITCH;
    public static final EntityType<? extends Mob> WITHER = EntityType.WITHER;
    public static final EntityType<? extends Mob> WITHER_SKELETON = EntityType.WITHER_SKELETON;
    public static final EntityType<? extends Mob> WOLF = EntityType.WOLF;
    public static final EntityType<? extends Mob> ZOGLIN = EntityType.ZOGLIN;
    public static final EntityType<? extends Mob> ZOMBIE = EntityType.ZOMBIE;
    public static final EntityType<? extends Mob> ZOMBIE_HORSE = EntityType.ZOMBIE_HORSE;
    public static final EntityType<? extends Mob> ZOMBIE_VILLAGER = EntityType.ZOMBIE_VILLAGER;
    public static final EntityType<? extends Mob> ZOMBIFIED_PIGLIN = EntityType.ZOMBIFIED_PIGLIN;
}
