package simplepets.brainsynder.nms;

import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EntityTypes;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.entity.monster.Shulker;

public class EntitySelector {
    public static final EntityType<? extends Mob> ALLAY = EntityTypes.ALLAY;
    public static final EntityType<? extends Mob> ARMADILLO = EntityTypes.ARMADILLO;
    public static final EntityType<? extends ArmorStand> ARMOR_STAND = EntityTypes.ARMOR_STAND;
    public static final EntityType<? extends Mob> AXOLOTL = EntityTypes.AXOLOTL;
    public static final EntityType<? extends Mob> BAT = EntityTypes.BAT;
    public static final EntityType<? extends Mob> BEE = EntityTypes.BEE;
    public static final EntityType<? extends Mob> BLAZE = EntityTypes.BLAZE;
    public static final EntityType<? extends Mob> BOGGED = EntityTypes.BOGGED;
    public static final EntityType<? extends Mob> BREEZE = EntityTypes.BREEZE;
    public static final EntityType<? extends Mob> CAMEL = EntityTypes.CAMEL;
    public static final EntityType<? extends Mob> CAMEL_HUSK = EntityTypes.CAMEL_HUSK;
    public static final EntityType<? extends Mob> CAT = EntityTypes.CAT;
    public static final EntityType<? extends Mob> CAVE_SPIDER = EntityTypes.CAVE_SPIDER;
    public static final EntityType<? extends Mob> CHICKEN = EntityTypes.CHICKEN;
    public static final EntityType<? extends Mob> COD = EntityTypes.COD;
    public static final EntityType<? extends Mob> COPPER_GOLEM = EntityTypes.COPPER_GOLEM;
    public static final EntityType<? extends Mob> COW = EntityTypes.COW;
    public static final EntityType<? extends Mob> CREAKING = EntityTypes.CREAKING;
    public static final EntityType<? extends Mob> CREEPER = EntityTypes.CREEPER;
    public static final EntityType<? extends Mob> DOLPHIN = EntityTypes.DOLPHIN;
    public static final EntityType<? extends Mob> DONKEY = EntityTypes.DONKEY;
    public static final EntityType<? extends Mob> DROWNED = EntityTypes.DROWNED;
    public static final EntityType<? extends Mob> ELDER_GUARDIAN = EntityTypes.ELDER_GUARDIAN;
    public static final EntityType<? extends Mob> ENDERMAN = EntityTypes.ENDERMAN;
    public static final EntityType<? extends Mob> ENDERMITE = EntityTypes.ENDERMITE;
    public static final EntityType<? extends Mob> EVOKER = EntityTypes.EVOKER;
    public static final EntityType<? extends Mob> FOX = EntityTypes.FOX;
    public static final EntityType<? extends Mob> FROG = EntityTypes.FROG;
    public static final EntityType<? extends Mob> GHAST = EntityTypes.GHAST;
    public static final EntityType<? extends Mob> GIANT = EntityTypes.GIANT;
    public static final EntityType<? extends Mob> GLOW_SQUID = EntityTypes.GLOW_SQUID;
    public static final EntityType<? extends Mob> GOAT = EntityTypes.GOAT;
    public static final EntityType<? extends Mob> GUARDIAN = EntityTypes.GUARDIAN;
    public static final EntityType<? extends Mob> HAPPY_GHAST = EntityTypes.HAPPY_GHAST;
    public static final EntityType<? extends Mob> HOGLIN = EntityTypes.HOGLIN;
    public static final EntityType<? extends Mob> HORSE = EntityTypes.HORSE;
    public static final EntityType<? extends Mob> HUSK = EntityTypes.HUSK;
    public static final EntityType<? extends Mob> ILLUSIONER = EntityTypes.ILLUSIONER;
    public static final EntityType<? extends Mob> IRON_GOLEM = EntityTypes.IRON_GOLEM;
    public static final EntityType<? extends Mob> LLAMA = EntityTypes.LLAMA;
    public static final EntityType<? extends Mob> MAGMA_CUBE = EntityTypes.MAGMA_CUBE;
    public static final EntityType<? extends Mob> MOOSHROOM = EntityTypes.MOOSHROOM;
    public static final EntityType<? extends Mob> MULE = EntityTypes.MULE;
    public static final EntityType<? extends Mob> NAUTILUS = EntityTypes.NAUTILUS;
    public static final EntityType<? extends Mob> OCELOT = EntityTypes.OCELOT;
    public static final EntityType<? extends Mob> PANDA = EntityTypes.PANDA;
    public static final EntityType<? extends Mob> PARCHED = EntityTypes.PARCHED;
    public static final EntityType<? extends Mob> PARROT = EntityTypes.PARROT;
    public static final EntityType<? extends Mob> PHANTOM = EntityTypes.PHANTOM;
    public static final EntityType<? extends Mob> PIG = EntityTypes.PIG;
    public static final EntityType<? extends Mob> PIGLIN = EntityTypes.PIGLIN;
    public static final EntityType<? extends Mob> PIGLIN_BRUTE = EntityTypes.PIGLIN_BRUTE;
    public static final EntityType<? extends Mob> PILLAGER = EntityTypes.PILLAGER;
    public static final EntityType<? extends Mob> POLAR_BEAR = EntityTypes.POLAR_BEAR;
    public static final EntityType<? extends Mob> PUFFERFISH = EntityTypes.PUFFERFISH;
    public static final EntityType<? extends Mob> RABBIT = EntityTypes.RABBIT;
    public static final EntityType<? extends Mob> RAVAGER = EntityTypes.RAVAGER;
    public static final EntityType<? extends Mob> SALMON = EntityTypes.SALMON;
    public static final EntityType<? extends Mob> SHEEP = EntityTypes.SHEEP;
    public static final EntityType<? extends Shulker> SHULKER = EntityTypes.SHULKER;
    public static final EntityType<? extends Mob> SILVERFISH = EntityTypes.SILVERFISH;
    public static final EntityType<? extends Mob> SKELETON = EntityTypes.SKELETON;
    public static final EntityType<? extends Mob> SKELETON_HORSE = EntityTypes.SKELETON_HORSE;
    public static final EntityType<? extends Mob> SLIME = EntityTypes.SLIME;
    public static final EntityType<? extends Mob> SNIFFER = EntityTypes.SNIFFER;
    public static final EntityType<? extends Mob> SNOW_GOLEM = EntityTypes.SNOW_GOLEM;
    public static final EntityType<? extends Mob> SPIDER = EntityTypes.SPIDER;
    public static final EntityType<? extends Mob> SQUID = EntityTypes.SQUID;
    public static final EntityType<? extends Mob> STRAY = EntityTypes.STRAY;
    public static final EntityType<? extends Mob> STRIDER = EntityTypes.STRIDER;
    public static final EntityType<? extends Mob> SULFUR_CUBE = EntityTypes.SULFUR_CUBE;
    public static final EntityType<? extends Mob> TADPOLE = EntityTypes.TADPOLE;
    public static final EntityType<? extends Mob> TRADER_LLAMA = EntityTypes.TRADER_LLAMA;
    public static final EntityType<? extends Mob> TROPICAL_FISH = EntityTypes.TROPICAL_FISH;
    public static final EntityType<? extends Mob> TURTLE = EntityTypes.TURTLE;
    public static final EntityType<? extends Mob> VEX = EntityTypes.VEX;
    public static final EntityType<? extends Mob> VILLAGER = EntityTypes.VILLAGER;
    public static final EntityType<? extends Mob> VINDICATOR = EntityTypes.VINDICATOR;
    public static final EntityType<? extends Mob> WANDERING_TRADER = EntityTypes.WANDERING_TRADER;
    public static final EntityType<? extends Mob> WARDEN = EntityTypes.WARDEN;
    public static final EntityType<? extends Mob> WITCH = EntityTypes.WITCH;
    public static final EntityType<? extends Mob> WITHER = EntityTypes.WITHER;
    public static final EntityType<? extends Mob> WITHER_SKELETON = EntityTypes.WITHER_SKELETON;
    public static final EntityType<? extends Mob> WOLF = EntityTypes.WOLF;
    public static final EntityType<? extends Mob> ZOGLIN = EntityTypes.ZOGLIN;
    public static final EntityType<? extends Mob> ZOMBIE = EntityTypes.ZOMBIE;
    public static final EntityType<? extends Mob> ZOMBIE_HORSE = EntityTypes.ZOMBIE_HORSE;
    public static final EntityType<? extends Mob> ZOMBIE_NAUTILUS = EntityTypes.ZOMBIE_NAUTILUS;
    public static final EntityType<? extends Mob> ZOMBIE_VILLAGER = EntityTypes.ZOMBIE_VILLAGER;
    public static final EntityType<? extends Mob> ZOMBIFIED_PIGLIN = EntityTypes.ZOMBIFIED_PIGLIN;
}
